docker pull apache/airflow:2.7.3
docker pull minio/minio:latest
docker pull fjardim/mds-namenode
docker pull fjardim/mds-datanode
docker pull fjardim/mds-kafka-zookeeper
docker pull fjardim/mds-kafka-broker
docker pull fjardim/mds-kafka-schema-registry
docker pull fjardim/mds-kafka-connect
docker pull fjardim/mds-kafka-control-center
docker pull fjardim/mds-kafka-ksqldb-server
docker pull fjardim/mds-kafka-sqldb-cli
docker pull fjardim/mds-kafka-rest
docker pull apache/nifi:latest
docker pull redis:latest
docker pull prestodb/presto
docker pull postgres
docker pull adminer
docker pull mysql
docker pull mongo
docker pull mongo-express
docker pull fjardim/mds-hive
docker pull fjardim/mds-hive-metastore
docker pull elasticsearch:7.10.1
docker pull cassandra:latest
docker pull ipushc/cassandra-web
docker pull clickhouse/clickhouse-server
docker pull metabase/metabase:latest
docker pull kibana:7.10.1
docker pull fjardim/mds-spark
docker pull "grafana/grafana"
docker pull "prom/prometheus"
docker pull "sscaling/jmx-prometheus-exporter"
docker pull elkozmon/zoonavigator
docker pull tchiotludo/akhq
docker pull fernandos/kafka-net
docker pull quay.io/keycloak/keycloak:20.0.2
docker pull quay.io/microcks/microcks-postman-runtime:latest
docker pull quay.io/microcks/microcks:1.7.1
docker pull quay.io/microcks/microcks-async-minion:1.7.1
docker pull fernandos/kafka-connet-debezium-lab    
docker pull dpage/pgadmin4
